# Generated by Django 2.1.15 on 2020-06-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles_2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Article_2',
        ),
    ]
