# Generated by Django 2.1.15 on 2020-06-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200617_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
