# Generated by Django 3.0.7 on 2020-06-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
